### ISSUE TITLE
"no such command: manual-indent-enable" errors 

### ISSUE THREAD

**Issue by DERPSQUID9** [alexherbo2/manual-indent.kak#1]
If I try to enter `manual-indent-enable` or any of the other commands mentioned in the README.md file into the prompt, not only does it not show up in the menu as I type, but I get an error saying that no such command exists. Similar errors also show up in the `*debug*` buffer if I use any of the commands in my kakrc.

**Comment by alexherbo2** [comment]
Once sourced, add to your kakrc:

``` kak
require-module manual-indent
```

**Comment by DERPSQUID9** [comment]
Thank you. That fixed it. Sorry for not trying that before I made this issue.
